### ISSUE TITLE
Local dapp serving and dev environment

### ISSUE THREAD

**Issue by paulbellamy** [stellar/soroban-cli#40]
A local way for devs to manually test their entire dapp e2e with a browser. They will want a way to have a local mock stellar network, running their contract, so that their javascript web app has something to talk to.

## TODO
- [ ] add `stellar-contract-cli serve` or `stellar-contract-cli sandbox`? command
- [ ] Design sandbox storage (json file on-disk?)
- [ ] Serve the contract RPC endpoint for queries
- [ ] Simulate txn submission & applying in the sandbox

**Comment by paulbellamy** [comment]
`$ stellar-contract-cli serve` maybe? or `$ stellar-contract-cli sandbox serve`?

**Comment by paulbellamy** [comment]
Duplicate of https://github.com/stellar/soroban-cli/issues/40
